name: Deploy Website to West Host
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: FTP upload files
        uses: SamKirkland/FTP-Deploy-Action@4.4.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PWD }}
          local-dir: ./
          server-dir: /var/ftp/pub/wafulock/
          clean-server: false
