name: Deploy to Aliyun ECS via SSH

on:
  push:
    branches: [ main ]  # 当推送到 main 分支时触发部署

jobs:
  deploy:
    name: Deploy code to server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          source: "."
          target: "/home/web/wafulock"
          strip_components: 1  # 避免创建额外目录层级
          rm: true             # 删除服务器上已不存在的文件（可选）